#!/bin/sh

#-------------------------------------------------------------------------------
# Description: This script is designed to automatically remove snaps that are marked as disabled.
# Licensing: This code is released under the MIT License. For more information, see <https://opensource.org/licenses/MIT>.
# Copyright (c) 2024 Mario Herrmann. All rights reserved.
#-------------------------------------------------------------------------------

LOCALE=${LANG%%.*}

case $LOCALE in
  en_US) DISABLED="disabled";;
  de_DE) DISABLED="deaktiviert";;
  fr_FR) DISABLED="désactivé";;
  it_IT) DISABLED="disabilitato";;
  es_ES) DISABLED="desactivado";;
  pt_PT) DISABLED="desativado";;
  nl_NL) DISABLED="uitgeschakeld";;
  pl_PL) DISABLED="wyłączony";;
  ru_RU) DISABLED="отключен";;
  sv_SE) DISABLED="inaktiverad";;
  da_DK) DISABLED="deaktiveret";;
  no_NO) DISABLED="deaktivert";;
  fi_FI) DISABLED="pois kiinni";;
  cs_CZ) DISABLED="deaktivován";;
  hu_HU) DISABLED="kikapcsolva";;
  el_GR) DISABLED="απενεργοποιημένο";;
  *) DISABLED="disabled";;
esac

snap list --all | awk "/$DISABLED/{print \$1, \$3}" |
  while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done