#!/bin/sh

#-------------------------------------------------------------------------------
# Description: This script is designed to automatically remove snaps that are marked as disabled.
# Licensing: This code is released under the MIT License. For more information, see <https://opensource.org/licenses/MIT>.
# Copyright (c) 2024 Mario Herrmann. All rights reserved.
#-------------------------------------------------------------------------------

local_lang=$LANG
LANG=C

snap list --all | awk "/disabled/{print \$1, \$3}" |
  while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done

LANG=$local_lang