#!/bin/sh

#-------------------------------------------------------------------------------
# Description: This script is designed to automatically remove snaps that are marked as disabled.
# Licensing: This code is released under the MIT License. For more information, see <https://opensource.org/licenses/MIT>.
# Copyright (c) 2024 Mario Herrmann. All rights reserved.
#-------------------------------------------------------------------------------

LANG=$(locale -a | grep -oP '(en_US|de_DE|fr_FR)')

case $LANG in
  en_US) DISABLED="disabled";;
  de_DE) DISABLED="deaktiviert";;
  fr_FR) DISABLED="désactivé";;
  *) DISABLED="disabled";;
esac

snap list --all | awk "/$DISABLED/{print \$1, \$3}" |
  while read snapname revision; do
    sudo snap remove "$snapname" --revision="$revision"
  done